"""add phone number

Revision ID: 2d8174e37172
Revises: 57dc07fd7e3a
Create Date: 2022-02-17 13:07:56.822553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d8174e37172'
down_revision = '57dc07fd7e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
